config/routes.rb
TaskScheduler::Engine.routes.draw do

  root :to => 'scheduled_tasks#index'

  resources :scheduled_tasks

  # move a legacy route
  get "/task_scheduler" => redirect("/scheduled_tasks")

end

app/models/task_scheduler/scheduled_task.rb
module TaskScheduler
  class ScheduledTask < ActiveRecord::Base
    has_many :scheduled_task_runs, :dependent => :destroy, :order => 'created_at desc'

    States = {
      :sleep => 0,
      :run => 1,
      :disabled => 2,
    }

    scope :ready_to_run, -> { where("next_run <= NOW() and state = #{TaskScheduler::ScheduledTask::States[:sleep]}").order(:next_run) }

    def ran( report )
      if self.next_run < self.started
        self.next_run = self.started
      end
      self.update_attributes( {
        :last_run => self.started,
        :started => nil,
        :next_run => self.next_run + self.interval_seconds,
        :state => States[:sleep]
        } )
      self.scheduled_task_runs.create({:report => report.inspect})
    end

    def running
      self.update_attributes( :state => States[:run], :started => Time.now )
    end

    def args_array
      self.args ? self.args.split(self.args_sep) : []
    end

  end
end

app/models/task_scheduler/scheduled_task_run.rb
module TaskScheduler
  class ScheduledTaskRun < ActiveRecord::Base
    belongs_to :scheduled_task
  end
end

app/controllers/task_scheduler/scheduled_tasks_controller.rb
module TaskScheduler
  class ScheduledTasksController < ApplicationController

    layout 'admin'

    before_filter :task_scheduler_access_control # must be implemented by the hosting app

    # GET /scheduled_tasks
    # GET /scheduled_tasks.json
    def index
      @scheduled_tasks = ScheduledTask.paginate(
        :per_page => 20,
        :page => params[:page]
      )

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @scheduled_tasks }
      end
    end

    # GET /scheduled_tasks/1
    # GET /scheduled_tasks/1.json
    def show
      @scheduled_task = ScheduledTask.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @scheduled_task }
      end
    end

    # GET /scheduled_tasks/new
    # GET /scheduled_tasks/new.json
    def new
      @scheduled_task = ScheduledTask.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @scheduled_task }
      end
    end

    # GET /scheduled_tasks/1/edit
    def edit
      @scheduled_task = ScheduledTask.find(params[:id])
    end

    # POST /scheduled_tasks
    # POST /scheduled_tasks.json
    def create
      @scheduled_task = ScheduledTask.new(params[:scheduled_task])
      p = params[:scheduled_task]
      d = DateTime.new(p["next_run(1i)"].to_i, p["next_run(2i)"].to_i, p["next_run(3i)"].to_i, p["next_run(4i)"].to_i, p["next_run(5i)"].to_i)
      @scheduled_task.next_run = d

      respond_to do |format|
        if @scheduled_task.save
          format.html { redirect_to @scheduled_task, notice: 'Scheduled task was successfully created.' }
          format.json { render json: @scheduled_task, status: :created, location: @scheduled_task }
        else
          format.html { render action: "new" }
          format.json { render json: @scheduled_task.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /scheduled_tasks/1
    # PUT /scheduled_tasks/1.json
    def update
      @scheduled_task = ScheduledTask.find(params[:id])

      respond_to do |format|
        if @scheduled_task.update_attributes(params.require(:scheduled_task).permit!)
          format.html { redirect_to @scheduled_task, notice: 'Scheduled task was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @scheduled_task.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /scheduled_tasks/1
    # DELETE /scheduled_tasks/1.json
    def destroy
      @scheduled_task = ScheduledTask.find(params[:id])
      @scheduled_task.destroy

      respond_to do |format|
        format.html { redirect_to scheduled_tasks_url, notice: 'Scheduled task was successfully destroyed.'  }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/task_scheduler/application_helper.rb
module TaskScheduler
  module ApplicationHelper
  end
end

app/helpers/task_scheduler/scheduled_tasks_helper.rb
module TaskScheduler
  module ScheduledTasksHelper
    def select_state?(state)
      @scheduled_task.state == state ? ' selected="selected"' : ''
    end

    def format_datetime(dt)
      return '' unless dt
      dt.strftime("%Y/%m/%d %H:%M:%S")
    end

  end
end

app/views/layouts/nav/task_scheduler/_primary.html.erb
<li><%= link_to( 'Tasks', :scheduled_tasks ) %></li>
<li><%= link_to( 'New Task', :new_scheduled_task ) %></li>

app/views/layouts/nav/task_scheduler/scheduled_tasks/_primary.html.erb
<%= render( 'layouts/nav/task_scheduler/primary') %>

app/views/task_scheduler/scheduled_tasks/_form.html.erb
<%= form_for(@scheduled_task) do |f| %>
  <% if @scheduled_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduled_task.errors.count, "error") %> prohibited this scheduled_task from being saved:</h2>

      <ul>
      <% @scheduled_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rake_method %><br />
    <%= f.text_field :rake_method %>
    e.g. <strong>log:clear</strong>
  </div>
  <div class="field">
    <%= f.label :args %><br />
    <%= f.text_field :args %>
    e.g. <strong>RAILS_ENV=production:user=1</strong>
  </div>
  <div class="field">
    <%= f.label :args_sep %><br />
    <%= f.text_field :args_sep %>
    <strong>Separates fields in Args</strong>
  </div>
  <div class="field">
    <%= f.label :notify_email %><br />
    <%= f.text_field :notify_email %>
    e.g. <strong>systemadmin@example.com</strong>
  </div>
  <div class="field">
    <%= f.label :interval_seconds %><br />
    <%= f.number_field :interval_seconds %>
    <strong>cron should run as frequently as the lowest ScheduledTask interval</strong>
  </div>
  <div class="field">
    <%= f.label :next_run %><br />
    <%= f.datetime_select :next_run %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <select id="scheduled_task_state" name="scheduled_task[state]">
      <option value="1"<%= select_state?(1) %>disabled='disabled'>running</option>
      <option value="0"<%= select_state?(0) %>>sleeping</option>
      <option value="2"<%= select_state?(2) %>>disabled</option>
    </select>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_scheduler/scheduled_tasks/_task_row.html.erb
<td><strong><%= scheduled_task.rake_method %>(<%= scheduled_task.args %>)</strong></td>
<td><%= format_datetime(scheduled_task.next_run) %></td>
<td><%= format_datetime(scheduled_task.last_run) %></td>
<td><%= TaskScheduler::ScheduledTask::States.select { |k,v| v == scheduled_task.state.to_i }.keys[0] %>
	<% if TaskScheduler::ScheduledTask::States[:run] == scheduled_task.state %><br />(<%= format_datetime(scheduled_task.started) %>)<% end %></td>

app/views/task_scheduler/scheduled_tasks/edit.html.erb
<h1>Editing scheduled_task</h1>

<h3>Current Time: <%= format_datetime(Time.now) %></h3>

<%= render 'form' %>

<%= link_to 'Show', @scheduled_task %> |
<%= link_to 'Back', scheduled_tasks_path %>

app/views/task_scheduler/scheduled_tasks/index.html.erb
<% @page_title = 'Listing Tasks' %>

<h3>Current Time: <%= format_datetime(Time.now) %></h3>

<table cellpadding='2'>
<tr>
	<th></th>
	<th></th>
	<th>Task</th>
	<th>Next Run</th>
	<th>Last Run</th>
	<th>State</th>
</tr>

<% for scheduled_task in @scheduled_tasks %>
<tr class='row<%= cycle(1,2) %>'>
  <td><%= link_to( 'Task Runs', :action => 'show', :id => scheduled_task) %></td>
  <td><%= link_to( 'Edit', :action => 'edit', :id => scheduled_task) %></td>
  <%= render( :partial => 'task_row', :locals => {:scheduled_task => scheduled_task } )%>
  <td><%= link_to( 'Destroy',  scheduled_task, :confirm => 'Are you sure?', :method => :delete) %></td>
</tr>
<% end %>
</table>
<div><%= will_paginate( @scheduled_tasks ) %></div>

<br />

<%= link_to( 'New scheduled task', :new_scheduled_task) %>


<p>
A system "cron job" triggers the Task Scheduler at a frequent interval (normally every hour).
The Task Scheduler triggers a run of any Task with a scheduled "Next Run" in the past.
When the Task has completed the run, the Task's "Interval Seconds" is added to
the "Next Run" time and the new Next Run value is saved back to the database.
</p><p>
If a Task State is set to Run for longer than it should be, it is probably stuck. The rake task task_scheduler:cleanup_task_runs
will probably clean it up within 24 hours or it can be run from the command line.
</p>

app/views/task_scheduler/scheduled_tasks/new.html.erb
<h1>New scheduled_task</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduled_tasks_path %>

app/views/task_scheduler/scheduled_tasks/show.html.erb
<% @page_title = "Task Runs" %>

<h2><%= @scheduled_task.rake_method.titleize %> (<%= @scheduled_task.scheduled_task_runs.size %>)</h2>

<table cellpadding='2'>
<% @scheduled_task.scheduled_task_runs.each { |e| %>
<tr class='row<%= cycle(1,2) %>'>
	<td>
	<h3><%= e.created_at %><h3>
	<pre><%= e.report.gsub('\n', "\n").sub(/^"?(.*)"?\S+$/, '\1') %></pre>
	</td>
</tr>	                                
<% } %>
</table>

app/views/task_scheduler/task_scheduler/list.html.erb
<% @page_title = 'Listing Tasks' %>

<h3>Current Time: <%= Time.now.strftime("%Y/%m/%d %H:%M:%S") %></h3>

<table cellpadding='2'>
<tr>
	<th></th>
	<th></th>
	<th>Task</th>
	<th>Next Run</th>
	<th>Last Run</th>
	<th>State</th>
</tr>	

<% for scheduled_task in @scheduled_tasks %>
<tr class='row<%= cycle(1,2) %>'>
  <td><%= link_to( 'Task Runs', :action => 'show', :id => scheduled_task) %></td>
  <td><%= link_to( 'Edit', :action => 'edit', :id => scheduled_task) %></td>
<%= render( :partial => 'task_row', :locals => {:scheduled_task => scheduled_task } )%>
  <td><%= link_to( 'Destroy', { :action => 'destroy', :id => scheduled_task }, :confirm => 'Are you sure?', :method => :post) %></td>
</tr>	
<% end %>
</table>
<div><%= will_paginate( @scheduled_tasks ) %></div>

<br />

<%= link_to( 'New scheduled task', :action => 'new') %>


<p>
A system "cron job" triggers the Task Scheduler at a frequent interval (normally every 15 minutes). 
The Task Scheduler triggers a run of any Task with a scheduled "Next Run" in the past. 
When the Task has completed the run, the Task's "Interval Seconds" is added to 
the "Next Run" time and the new Next Run value is saved back to the database.
</p><p>
If a Task State is set to Run for longer than it should be, it is probably stuck. The rake task task_scheduler:cleanup_task_runs 
will probably clean it up within 24 hours or it can be run from the command line.
</p>